spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163
          uri: http://www.163.com/
          predicates:
          - Path=/163/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 20
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"
          - name: Retry
            args:
              retries: 3
              status: 404
              statusSeries: 500
              method: GET
          - JwtCheck
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
server:
  port: 5001


